# Generated by Django 4.0.4 on 2023-02-22 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PdfFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('file', models.FileField(upload_to='static')),
            ],
        ),
        migrations.CreateModel(
            name='PdfFilepath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('path', models.FilePathField(path='static/')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.pdffile')),
            ],
        ),
    ]
