# Generated by Django 4.1.5 on 2023-03-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('website', models.CharField(max_length=2000)),
                ('biz_code', models.CharField(max_length=2000)),
            ],
        ),
    ]
