# Generated by Django 4.1.5 on 2023-04-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0002_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='template',
            field=models.CharField(choices=[('Poor', 'Poor'), ('Meh', 'Meh'), ('Mid', 'Mid'), ('Decent', 'Decent'), ('Rad', 'Rad')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='text',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
