# Generated by Django 4.1.5 on 2023-04-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0003_business_template_business_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='user_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='biz_code',
            field=models.CharField(max_length=2000, unique=True),
        ),
    ]
