# Generated by Django 4.1.5 on 2023-04-14 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0005_receiptrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiptrequest',
            old_name='name',
            new_name='receipt_name',
        ),
    ]
