# Generated by Django 4.1.5 on 2023-04-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0006_rename_name_receiptrequest_receipt_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptrequest',
            name='user_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
