# Generated by Django 4.1.5 on 2023-06-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0008_alter_receiptrequest_user_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptrequest',
            name='timeanddate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
