# Generated by Django 4.1.5 on 2023-06-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlogs',
            name='pay_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
