# Generated by Django 4.1.5 on 2023-06-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='receipt_allocation',
            field=models.IntegerField(default=20),
        ),
    ]
